# Generated by Django 5.0.2 on 2024-10-20 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_dos_api', '0003_alumno_maestro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
        migrations.RenameModel(
            old_name='Maestro',
            new_name='Maestros',
        ),
    ]
