# Generated by Django 5.0.2 on 2024-10-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_dos_api', '0004_rename_alumno_alumnos_rename_maestro_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias_impartidas',
            new_name='materias_json',
        ),
    ]
