# Generated by Django 5.0.2 on 2024-11-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_dos_api', '0005_rename_materias_impartidas_maestros_materias_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='clave_maestro',
            new_name='id_trabajador',
        ),
    ]
